V3_VERSION = "3.0.0"
SCHEMA_VERSION_V3 = V3_VERSION
RUNTIME_RECORD_VERSION_V3 = V3_VERSION
SCORER_VERSION_V3 = V3_VERSION
METRIC_REGISTRY_VERSION_V3 = V3_VERSION
TASK_MANIFEST_VERSION_V3 = V3_VERSION
RUN_MANIFEST_VERSION_V3 = V3_VERSION
ADAPTER_CONTRACT_VERSION_V3 = V3_VERSION
COMPILER_VERSION_V3 = V3_VERSION
PROFILE_VERSION_V3 = V3_VERSION
PRIMARY_FAILURE_PRECEDENCE_VERSION_V3 = V3_VERSION

__all__ = [
    "ADAPTER_CONTRACT_VERSION_V3",
    "COMPILER_VERSION_V3",
    "METRIC_REGISTRY_VERSION_V3",
    "PRIMARY_FAILURE_PRECEDENCE_VERSION_V3",
    "PROFILE_VERSION_V3",
    "RUN_MANIFEST_VERSION_V3",
    "RUNTIME_RECORD_VERSION_V3",
    "SCHEMA_VERSION_V3",
    "SCORER_VERSION_V3",
    "TASK_MANIFEST_VERSION_V3",
    "V3_VERSION",
]
